BookReviews/BookReviews/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('comments/', include('django_comments.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('books.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookReviews/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('authors/', views.AuthorsView.as_view(), name='authors_list'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author_details'),
    path('books/', views.BooksView.as_view(), name='books_list'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('genres/', views.GenresView.as_view(), name='genres_list'),
    path('genres/<int:pk>', views.GenreDetailView.as_view(), name='genre_details'),
]

BookReviews/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('<int:book_id>/add/', views.AddReview.as_view(), name='add_review'),
    path('<int:book_id>/<int:review_id>/edit/', views.EditReview.as_view(), name='edit_review'),
    path('<int:book_id>/<int:review_id>/delete/', views.DeleteReview.as_view(), name='delete_review'),
    path('<int:book_id>/<int:review_id>/publish/', views.PublishReview.as_view(), name='publish_review'),
    path('list/', views.ListReviews.as_view(), name='reviews_list'),
]

BookReviews/books/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone


class Author(models.Model):
	first_name = models.CharField(
		max_length=64,
		help_text='',
		verbose_name='First name',
	)
	last_name = models.CharField(
		max_length=64,
		help_text='',
		verbose_name='Last name',
	)
	about = models.TextField(
		blank=True,
		null=True,
		help_text='',
		verbose_name='About author',
	)
	birth_date = models.DateField(
		blank=True,
		null=True,
		help_text='',
		verbose_name='Birth date',
	)
	website = models.URLField(
		blank=True,
		null=False,
		default='',
		help_text='',
		verbose_name='Website',
	)
	email = models.EmailField(
		blank=True,
		null=True,
		help_text='',
		verbose_name='Email',
	)
	rating = models.PositiveSmallIntegerField(
		blank=True,
		null=True,
		help_text='',
		verbose_name='Rating',
		validators=[
			MinValueValidator(0),
			MaxValueValidator(10),
		]
	)
	created = models.DateTimeField(
		default=timezone.now,
		verbose_name='Created',
	)
	updated = models.DateTimeField(
		default=timezone.now,
		verbose_name='Last update',
	)

	def save(self, *args, **kwargs):
		self.updated = timezone.now()
		super(Author, self).save(*args, **kwargs)

	def __str__(self):
		return f'{self.first_name} {self.last_name}'


class Book(models.Model):
	title = models.CharField(
		max_length=200,
		help_text='',
		verbose_name='Title',
	)
	author = models.ForeignKey(
		Author, on_delete=models.CASCADE,
		help_text='',
		verbose_name='Author',
	)
	genres = models.ManyToManyField(
		'Genre',
		default='General',
		help_text='',
		verbose_name='Genre',
	)
	pages = models.PositiveSmallIntegerField(
		blank=True,
		null=True,
		verbose_name='Pages',
	)
	description = models.TextField(
		blank=True,
		null=True,
		help_text='',
		verbose_name='Description',
	)
	added = models.DateTimeField(
		default=timezone.now,
		verbose_name='Added on',
	)
	updated = models.DateTimeField(
		default=timezone.now,
		verbose_name='Last update',
	)
	book_cover = models.ImageField(
		upload_to='static',
		default='',
		blank=True,
		null=True,
		verbose_name='Cover image',
		help_text='',
	)

	def save(self, *args, **kwargs):
		self.updated = timezone.now()
		super(Book, self).save(*args, **kwargs)

	def __str__(self):
		return f'{self.title}'


class Genre(models.Model):
	name = models.CharField(
		max_length=64,
		default='General',
		help_text='',
		verbose_name='Name',
	)
	description = models.TextField(
		blank=True,
		null=True,
		help_text='',
		verbose_name='Description',
	)
	added = models.DateTimeField(
		default=timezone.now,
		verbose_name='Added on',
	)

	def __str__(self):
		return self.name

BookReviews/reviews/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from books.models import Book


class ReviewManager(models.Manager):
	def published(self):
		return self.filter(status='published').order_by('-added')


class Review(models.Model):

	STATUS_CHOICES = [
		('draft', 'Draft'),
		('sent', 'Sent'),
		('rejected', 'Rejected'),
		('published', 'Published'),
	]

	user = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete=models.PROTECT,
		verbose_name='User',
		help_text='',
	)
	book = models.ForeignKey(
		Book, on_delete=models.CASCADE,
		verbose_name='Book',
		help_text='',
	)
	subject = models.CharField(
		max_length=200,
		verbose_name='Subject',
		help_text='',
	)
	content = models.TextField(
		verbose_name='Content',
		help_text='',
	)
	published = models.DateTimeField(
		default=timezone.now,
		verbose_name='Published',
	)
	status = models.CharField(
		choices=STATUS_CHOICES,
		max_length=64,
		verbose_name='Status',
		help_text='',
	)
	rating = models.PositiveSmallIntegerField(
		verbose_name='Rating',
		help_text='Values from 0 to 10',
		validators=[
			MinValueValidator(0),
			MaxValueValidator(10),
		]
	)
	added = models.DateTimeField(
		default=timezone.now,
		verbose_name='Added on',
	)
	updated = models.DateTimeField(
		default=timezone.now,
		verbose_name='Last update',
	)

	def save(self, *args, **kwargs):
		self.updated = timezone.now()
		if self.status == 'published' and not self.published:
			self.published = timezone.now()
		return super().save(*args, **kwargs)

	def __str__(self):
		return f'{self.book} | {self.subject}'

	objects = ReviewManager()


class Rating(models.Model):

	user = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		verbose_name='User',
		help_text='',
	)
	rating = models.PositiveSmallIntegerField(
		verbose_name='Rating',
		help_text='Values from 0 to 10',
		validators=[
			MinValueValidator(0),
			MaxValueValidator(10),
		],
	)
	book = models.ForeignKey(
		Book, on_delete=models.CASCADE,
		verbose_name='Book',
		help_text='',
	)

	def __str__(self):
		return f'Rating: {self.rating} | Book: {self.book}'

BookReviews/books/views.py
from django.db.models import Avg, Count
from django.shortcuts import reverse
from django.contrib.auth.mixins import AccessMixin
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import FormView
from django.views.generic.detail import SingleObjectMixin

from reviews.forms import RatingForm
from books.models import Author, Book, Genre


class IndexView(TemplateView):
	template_name = 'index.html'


class AuthorsView(ListView):
	template_name = 'books/authors.html'
	queryset = Author.objects.all()
	context_object_name = 'authors'


class AuthorDetailView(DetailView):
	model = Author
	template_name = 'books/author_details.html'
	# context_object_name = 'author'

	def get_context_data(self, **kwargs):
		context = {
			'title': f'Author {self.object}',
		}
		context.update(kwargs)
		return super().get_context_data(**context)


class BooksView(ListView):
	template_name = 'books/books.html'
	queryset = Book.objects.all()
	context_object_name = 'books'


class BookDetailView(AccessMixin, SingleObjectMixin, FormView):
	model = Book
	template_name = 'books/book_details.html'
	form_class = RatingForm
	permission_denied_message = 'Custom permission denied message'

	def get_success_url(self):
		return reverse('books:book_detail', kwargs={'pk': self.object.pk})

	def get(self, request, *args, **kwargs):
		self.object = self.get_object()
		context = self.get_context_data(object=self.object)
		return self.render_to_response(context)

	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return self.handle_no_permission()
		self.object = self.get_object()
		return super().post(request, *args, **kwargs)

	def form_valid(self, form):
		form.instance.user = self.request.user
		form.instance.book = self.object
		self.rating = form.save()
		return super().form_valid(form)

	def get_context_data(self, **kwargs):
		context = {
			'title': f'Book {self.object}',
			'avg_ratings': self.object.rating_set.aggregate(
				average=Avg('rating'), count=Count('rating')
			),
		}
		context.update(kwargs)
		return super().get_context_data(**context)


class GenresView(ListView):
	template_name = 'books/genres.html'
	queryset = Genre.objects.all()
	context_object_name = 'genres'


class GenreDetailView(DetailView):
	model = Genre
	template_name = 'books/genre_details.html'
	context_object_name = 'genres'

BookReviews/books/templates/books/author_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load comments %}


{% block content %}
	<h4 class="d-block py-5 mx-auto">Details for author: {{ author }}</h4>
	<div class="row">
		<div class="col-6">
			<h6>Books list:</h6>
			<ul>
				{% for book in author.book_set.all %}
					<li>
						<a href="{% url 'books:book_detail' book.pk %}">{{ book }}</a>
					</li>

				{% endfor %}
			</ul>
		</div>
		<div class="col-6">
			<h6>Author details:</h6>
			<table class="table table-hover">
				<tbody>
				<tr>
					<th scope="row">Name</th>
					<td>{{ author }}</td>
				</tr>
				<tr>
					<th scope="row">Birth date</th>
					<td>{{ author.birth_date|date:"D, d M Y" }}</td>
				</tr>
				<tr>
					<th scope="row">Website</th>
					<td>{{ author.website|urlize }}</td>
				</tr>
				<tr>
					<th scope="row">Email</th>
					<td>{{ author.email }}</td>
				</tr>
				<tr>
					<th scope="row">Rating</th>
					<td>{{ author.rating }}</td>
				</tr>
				</tbody>
			</table>
		</div>
	</div>


	<div class="row py-3 border-top-1 ">
		<div class="col">
			{% get_comment_count for author as comment_count %}
			<h4>Comments <span class="small">( {{ comment_count }} )</span></h4>
			{% get_comment_list for author as comment_list %}
			{% for comment in comment_list %}
				<blockquote class="blockquote border-left border-dark pl-2">
					<p class="mb-0 small">{{ comment.comment }}</p>
					<footer class="blockquote-footer">
{#						Added: {{ comment.submit_date|date:"D, d M Y" }}#}
						Added: {{ comment.submit_date|timesince }} ago by {{ comment.user_name }}
					</footer>
				</blockquote>
			{% endfor %}
		</div>
	</div>

	<div class="row">
		<div class="col">
			{% get_comment_form for author as form %}
			<p>Add crispy comment:</p>
			<form action="{% comment_form_target %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="next" value="{{ request.path }}"/>
				{{ form|crispy }}
				<tr>
					<td colspan="2">
						<input type="submit" name="submit" value="Post">
						<input type="submit" name="preview" value="Preview">
					</td>
				</tr>
			</form>

		</div>
	</div>
{% endblock %}

BookReviews/books/templates/books/authors.html
{% extends 'base.html' %}

{% block content %}
	<h3 class="d-block py-5 mx-auto">Authors</h3>

	{% if authors %}
		<ul>
			{% for author in authors %}
			<li>
				<a href="{% url 'books:author_details' author.pk %}">{{ author }}</a>
			</li>

			{% endfor %}
		</ul>
	{% else %}
		<p>No authors saved</p>
	{% endif %}

{% endblock %}

BookReviews/books/templates/books/book_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<h3 class="d-block py-5 mx-auto">Book details for "{{ book }}":</h3>
	<div class="row">
		<div class="col-6">
			{% if book.book_cover %}
				<img src="{{ book.book_cover.url }}" alt="Book cover"/>
			{% else %}
				&mdash;
			{% endif %}
		</div>
		<div class="col-6">
			<h6>Book details:</h6>
			<table class="table table-hover">
				<tbody>
				<tr>
					<th scope="row">Author</th>
					<td>{{ book.author }}</td>
				</tr>
				<tr>
					<th scope="row">Pages</th>
					<td>{{ book.pages|default_if_none:"&mdash;" }}</td>
				</tr>
				<tr>
					<th scope="row">Genre</th>
					<td>{% for genre in book.genres.all %}
						{{ genre }}
					{% empty %}
						&mdash;
					{% endfor %}</td>
				</tr>
				<tr>
					<th scope="row">Book rating</th>
					<td>
						{% if avg_ratings.average %}
							{{ avg_ratings.average|floatformat:2|default:"&mdash;" }}
						{% else %}
							&mdash;
						{% endif %}</td>
				</tr>
				<tr>
					<th scope="row">Ratings submitted</th>
					<td>
						{% if avg_ratings.count %}
							{{ avg_ratings.count|default:"&mdash;" }}
						{% else %}
							&mdash;
						{% endif %}
					</td>
				</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="row py-4">
		<div class="col-6">
			<div class="row d-flex justify-content-between">
				<div class="col-6">
					<h4>Book reviews:</h4>
				</div>
				<div class="col-6 d-flex justify-content-center">
					<a href="{% url 'reviews:add_review' book.pk %}">
						<span class="badge badge-primary p-2">Add book review</span>
					</a>
				</div>
				<div class="col">
					{% for review in book.review_set.published %}
						<blockquote class="blockquote border-left border-dark pl-2">
							<p class="mb-0 small">{{ review.content|safe }}</p>
							<footer class="blockquote-footer small">
								Added: {{ review.added|timesince }} ago by {{ review.user }}
							</footer>
						</blockquote>
					{% endfor %}
				</div>
			</div>


		</div>
		<div class="col-6">
			<p>Add your rating:</p>
			{% if request.user.is_authenticated %}
				<form method="post">
					{% csrf_token %}
					{{ form|crispy }}
					<button type="submit" class="btn btn-primary">Submit</button>
				</form>
			{% else %}
				You must be logged in to add rating or your comment
			{% endif %}
		</div>
	</div>

{% endblock %}

BookReviews/books/templates/books/books.html
{% extends 'base.html' %}

{% block content %}

	<h3 class="d-block py-5 mx-auto">Books</h3>

	{% if books %}
		<ul>
			{% for book in books %}
				<li>
					<a href="{% url 'books:book_detail' book.pk %}">{{ book }}</a>
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No books saved</p>
	{% endif %}


{% endblock %}

BookReviews/books/templates/books/genre_details.html
{% extends 'base.html' %}

{% block content %}
	<h3 class="d-block py-5 mx-auto">All books in {{ genre }}:</h3>

	<div class="row">
		<div class="col-6">
			<h6>Books list:</h6>
			<ul>
				{% for book in genres.book_set.all %}
					<li>
						<a href="{% url 'books:book_detail' book.pk %}">{{ book }}</a>
					</li>

				{% endfor %}
			</ul>
		</div>
	</div>

{% endblock %}

BookReviews/books/templates/books/genres.html
{% extends 'base.html' %}

{% block content %}

	<h3 class="d-block py-5 mx-auto">Genres</h3>

	{% if genres %}
		<ul>
			{% for genre in genres %}
				<li>
					<a href="{% url 'books:genre_details' genre.pk %}">{{ genre }}</a>
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No genres saved</p>
	{% endif %}

{% endblock %}