BookReviews/BookReviews/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('comments/', include('django_comments.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('books.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookReviews/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('authors/', views.AuthorsView.as_view(), name='authors_list'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author_details'),
    path('books/', views.BooksView.as_view(), name='books_list'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('genres/', views.GenresView.as_view(), name='genres_list'),
    path('genres/<int:pk>', views.GenreDetailView.as_view(), name='genre_details'),
]

BookReviews/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('<int:book_id>/add/', views.AddReview.as_view(), name='add_review'),
    path('<int:book_id>/<int:review_id>/edit/', views.EditReview.as_view(), name='edit_review'),
    path('<int:book_id>/<int:review_id>/delete/', views.DeleteReview.as_view(), name='delete_review'),
    path('<int:book_id>/<int:review_id>/publish/', views.PublishReview.as_view(), name='publish_review'),
    path('list/', views.ListReviews.as_view(), name='reviews_list'),
]

BookReviews/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

	{% include 'head.html' %}

</head>
<body>

{% include 'navbar.html' %}

{% include 'carousel.html' %}

<div class="container">
	<div class="row">
		<div class="col">
			{% block content %}

			{% endblock %}
		</div>
	</div>
</div>


{% include 'footer.html' %}

</body>
</html>

BookReviews/templates/carousel.html
{% load static %}

<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'books/img/banner.png' %}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'books/img/banner.png' %}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'books/img/banner.png' %}" alt="Third slide">
    </div>
  </div>
</div>

BookReviews/templates/footer.html
<hr>
<div class="container p-4">
	<div class="row">
		<div class="col d-flex flex-column align-items-center justify-content-center">
			<div class="small">Created by
				Grzegorz Lason</div>
			<div class="small">Copyright reserved</div>
		</div>
	</div>
</div>

BookReviews/templates/head.html
{% load static %}

<meta charset="UTF-8">
<title>{% if title %}Books Reviews &bull; {{ title }}{% else %}Books Review
	s{% endif %}</title>

<link rel="stylesheet" href="{% static 'books/css/bootstrap-grid.css' %}">
<link rel="stylesheet" href="{% static 'books/css/custom_bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'books/css/styles.css' %}">

BookReviews/templates/index.html
{% extends 'base.html' %}

{% block content %}

<h3 class="d-block py-5 mx-auto">Welcome to Book Reviews</h3>

{% endblock %}

BookReviews/templates/navbar.html
<div class="container">
	<div class="row">
		<div class="col">

			<nav class="navbar navbar-expand-lg navbar-light bg-light">
				<a class="navbar-brand" href="{% url 'books:index' %}">Books
					Reviews</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse"
				        data-target="#navbarSupportedContent"
				        aria-controls="navbarSupportedContent" aria-expanded="false"
				        aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item active">
							<a class="nav-link"
							   href="{% url 'books:books_list' %}">Books<span
									class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item active">
							<a class="nav-link"
							   href="{% url 'books:authors_list' %}">Authors</a>
						</li>
						<li class="nav-item active">
							<a class="nav-link"
							   href="{% url 'books:genres_list' %}">Genres</a>
						</li>
						<li class="nav-item active">
							{% if request.user.is_authenticated %}
								<a class="nav-link"
								   href="{% url 'reviews:reviews_list' %}">Your reviews</a>
							{% endif %}
						</li>
					</ul>
					<div class="d-block pl-2">
						{% if request.user.is_authenticated %}
							<button class="btn btn-outline-success my-2 my-sm-0"
							        type="button"
							        data-toggle="collapse">
								<a href="{% url 'logout' %}">Log Out</a>
							</button>
						{% else %}
							<button class="btn btn-outline-success my-2 my-sm-0"
							        type="button"
							        data-toggle="collapse">
								<a href="{% url 'login' %}">Log In</a>
							</button>
						{% endif %}
					</div>
				</div>
			</nav>
		</div>
	</div>
</div>