BookReviews/BookReviews/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('comments/', include('django_comments.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('books.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BookReviews/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('authors/', views.AuthorsView.as_view(), name='authors_list'),
    path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author_details'),
    path('books/', views.BooksView.as_view(), name='books_list'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('genres/', views.GenresView.as_view(), name='genres_list'),
    path('genres/<int:pk>', views.GenreDetailView.as_view(), name='genre_details'),
]

BookReviews/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('<int:book_id>/add/', views.AddReview.as_view(), name='add_review'),
    path('<int:book_id>/<int:review_id>/edit/', views.EditReview.as_view(), name='edit_review'),
    path('<int:book_id>/<int:review_id>/delete/', views.DeleteReview.as_view(), name='delete_review'),
    path('<int:book_id>/<int:review_id>/publish/', views.PublishReview.as_view(), name='publish_review'),
    path('list/', views.ListReviews.as_view(), name='reviews_list'),
]

BookReviews/reviews/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from books.models import Book


class ReviewManager(models.Manager):
	def published(self):
		return self.filter(status='published').order_by('-added')


class Review(models.Model):

	STATUS_CHOICES = [
		('draft', 'Draft'),
		('sent', 'Sent'),
		('rejected', 'Rejected'),
		('published', 'Published'),
	]

	user = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete=models.PROTECT,
		verbose_name='User',
		help_text='',
	)
	book = models.ForeignKey(
		Book, on_delete=models.CASCADE,
		verbose_name='Book',
		help_text='',
	)
	subject = models.CharField(
		max_length=200,
		verbose_name='Subject',
		help_text='',
	)
	content = models.TextField(
		verbose_name='Content',
		help_text='',
	)
	published = models.DateTimeField(
		default=timezone.now,
		verbose_name='Published',
	)
	status = models.CharField(
		choices=STATUS_CHOICES,
		max_length=64,
		verbose_name='Status',
		help_text='',
	)
	rating = models.PositiveSmallIntegerField(
		verbose_name='Rating',
		help_text='Values from 0 to 10',
		validators=[
			MinValueValidator(0),
			MaxValueValidator(10),
		]
	)
	added = models.DateTimeField(
		default=timezone.now,
		verbose_name='Added on',
	)
	updated = models.DateTimeField(
		default=timezone.now,
		verbose_name='Last update',
	)

	def save(self, *args, **kwargs):
		self.updated = timezone.now()
		if self.status == 'published' and not self.published:
			self.published = timezone.now()
		return super().save(*args, **kwargs)

	def __str__(self):
		return f'{self.book} | {self.subject}'

	objects = ReviewManager()


class Rating(models.Model):

	user = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		verbose_name='User',
		help_text='',
	)
	rating = models.PositiveSmallIntegerField(
		verbose_name='Rating',
		help_text='Values from 0 to 10',
		validators=[
			MinValueValidator(0),
			MaxValueValidator(10),
		],
	)
	book = models.ForeignKey(
		Book, on_delete=models.CASCADE,
		verbose_name='Book',
		help_text='',
	)

	def __str__(self):
		return f'Rating: {self.rating} | Book: {self.book}'

BookReviews/reviews/forms.py
from django import forms

from .models import Rating, Review


class RatingForm(forms.ModelForm):
	# rating = forms.IntegerField(max_value=10, min_value=0)

	class Meta:
		model = Rating
		fields = [
			'rating',
		]

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['rating'].widget = forms.NumberInput(
			attrs={'min': 0, 'max': 10}
		)


class ReviewForm(forms.ModelForm):

	class Meta:
		model = Review
		fields = [
			'subject',
			'content',
			'rating',
		]

BookReviews/reviews/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, reverse
from django.views.generic import UpdateView, View, FormView
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy

from books.models import Book
from .models import Review
from .forms import ReviewForm


class ListReviews(LoginRequiredMixin, ListView):
	template_name = 'reviews/reviews.html'
	context_object_name = 'reviews'

	def get_queryset(self):
		return Review.objects.filter(user=self.request.user)


class AddReview(LoginRequiredMixin, CreateView):
	model = Review
	form_class = ReviewForm
	template_name = 'reviews/review_add.html'
	success_url = reverse_lazy('reviews:reviews_list')

	def get_context_data(self, **kwargs):
		form = ReviewForm(instance=self.get_book())
		context = {
			'title': f'Edit review of {self.book}',
			'form': form,
		}
		context.update(kwargs)
		return super().get_context_data(**context)

	def get_book(self):
		book_id = self.kwargs.get('book_id')
		return get_object_or_404(Book, pk=book_id)

	def get(self, request, *args, **kwargs):
		self.book = self.get_book()
		return super().get(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		self.book = self.get_book()

		return super().post(request, *args, **kwargs)

	def form_valid(self, form):
		form.instance.user = self.request.user
		form.instance.book = self.book
		form.instance.status = 'draft'
		return super().form_valid(form)


class PublishReview(LoginRequiredMixin, View):

	def post(self, request, *args, **kwargs):
		review_id = self.kwargs.get('review_id')
		review = get_object_or_404(
			Review,
			pk=review_id,
			user=request.user,
			status='draft',
		)
		review.status = 'published'
		review.save()
		return redirect('reviews:reviews_list')


class EditReview(LoginRequiredMixin, UpdateView):
	model = Review
	template_name = 'reviews/review_edit.html'
	pk_url_kwarg = 'review_id'
	fields = ['subject', 'content', 'rating']
	success_url = reverse_lazy('reviews:reviews_list')

	def get_queryset(self):
		review_id = self.kwargs.get('review_id')
		return Review.objects.filter(id=review_id)

	def form_valid(self, form):
		form.instance.user = self.request.user
		form.instance.book = self.object.book
		form.instance.status = 'draft'
		return super().form_valid(form)

	def get_object(self, queryset=None):
		return Review.objects.get(id=self.kwargs['review_id'])

	def get_context_data(self, **kwargs):
		form = ReviewForm(instance=self.get_object())
		context = {
			'title': f'Edit review',
			'form': form,
		}
		return super().get_context_data(**context)


class DeleteReview(LoginRequiredMixin, DeleteView):
	model = Review
	pk_url_kwarg = 'review_id'
	success_url = reverse_lazy('reviews:reviews_list')

BookReviews/reviews/templates/reviews/review_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

	<h3 class="d-block py-5 mx-auto">Reviews</h3>

	<form method="POST" action="#">
		{% csrf_token %}

		{{ form|crispy }}
		<button type="submit">Submit</button>

	</form>




{% endblock %}

BookReviews/reviews/templates/reviews/review_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

	<h3 class="d-block py-5 mx-auto">Edit your review</h3>

	<form method="POST">
		{% csrf_token %}

		{{ form|crispy }}
		<button type="submit">Update</button>

	</form>




{% endblock %}

BookReviews/reviews/templates/reviews/reviews.html
{% extends 'base.html' %}

{% block content %}

	<h3 class="d-block py-5 mx-auto">Your reviews</h3>

	<table class="table table-hover">
		<thead>
		<tr>
			<th scope="col">Book</th>
			<th scope="col">Subject</th>
			<th scope="col">Content</th>
			<th scope="col">Rating</th>
			<th scope="col">Status</th>
			<th scope="col">Updated</th>
			<th scope="col">Actions</th>
		</tr>
		</thead>
		{% for review in reviews %}
			<tr>
				<td>{{ review.book }}</td>
				<td>{{ review.subject|safe }}</td>
				<td>{{ review.content|safe }}</td>
				<td>{{ review.rating }}</td>
				<td>{{ review.status }}</td>
				<td>{{ review.updated|date:"d M Y" }}</td>
				<td>
					<form method="POST" action="{% url 'reviews:delete_review' review.book.id review.id %}">
						{% csrf_token %}
						<button type="submit" class="badge badge-primary border-0">Delete</button>
					</form>
					<form method="POST" action="{% url 'reviews:edit_review' review.book.id review.id %}">
						{% csrf_token %}
						<button type="submit" class="badge badge-primary border-0">Edit</button>
					</form>
					<form method="POST" action="{% url 'reviews:publish_review' review.book.id review.id %}">
						{% csrf_token %}
						<button type="submit" class="badge badge-primary border-0">Publish</button>
					</form>
				</td>
			</tr>
		{% endfor %}
	</table>

{% endblock %}